# Generated by Django 2.1 on 2018-08-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='appuser',
            name='access_token',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
