# Generated by Django 2.1 on 2018-08-16 08:57

from django.db import migrations, models


# TODO reverse migration

def create_image_records_from_adverts(apps, schema_editor):
    """
    Create Image from every object of Advertisement photo field
    """
    Advertisement = apps.get_model('advertisement', "Advertisement")
    Image = apps.get_model('advertisement', 'Image')
    for advert in Advertisement.objects.all():
        image = Image(advertisement=advert, image=advert.photo)
        image.save()


def delete_image_records(apps, schema_editor):
    Image = apps.get_model('advertisement', "Image")
    Advertisement = apps.get_model('advertisement', "Advertisement")

    # Assign image field of Image object to photo field of Advertisement object
    for image in Image.objects.all():
        # take the last photo that belongs to advertisement
        advert = Advertisement.objects.filter(id=image.advertisement.id).last()
        advert.photo = image.image
        advert.save()


class Migration(migrations.Migration):
    dependencies = [
        ('advertisement', '0008_image'),
    ]

    # register our methods on migration
    # first method will be called when migration applies
    # second - if migration reverse
    operations = [
        migrations.RunPython(create_image_records_from_adverts, delete_image_records),  # make reverse migration
    ]
