# Generated by Django 2.1 on 2018-08-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_image_creating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='photo',
        ),
    ]
