# Generated by Django 2.1 on 2018-08-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_remove_advertisement_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
    ]
