# Generated by Django 2.1 on 2018-08-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat messages'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('link',), 'verbose_name': 'Chat room', 'verbose_name_plural': 'Chat rooms'},
        ),
    ]
