# Generated by Django 2.1 on 2018-08-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180808_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('link',)},
        ),
    ]
