# Generated by Django 2.1 on 2018-08-13 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180809_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.ChatRoom', verbose_name='Chat room'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_body',
            field=models.TextField(max_length=2500, verbose_name='Message text'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Message timestamp'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_user', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='link',
            field=models.URLField(unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL, verbose_name='Chat owner'),
        ),
    ]
